name: CI
on:
  push:
jobs:
  build-test-job:
    runs-on: ubuntu-latest
    container:
      image: rudicilibrasi/jen
      options: --cpus 1
    steps:
      - name: checkout
        uses: "actions/checkout@v4"
      - name: Run Build Test
        run: ./run-build-test
      - name: Run Emscripten Build Test
        run: ./run-emscripten-build-test
      - name: Run React Build Test
        run: ./run-react-test
