name: CI
on:
  push:
jobs:
  build-test-job:
    runs-on: ubuntu-latest
    container:
      image: rudicilibrasi/jen
      options: --cpus 1
    steps:
      - name: checkout
        uses: "actions/checkout@v4"
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Run Build Test
        run: ./run-build-test
