name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We will respond or assign your issue as soon as possible."
        pr-message: "Welcome to Our repository.🎊 Thank you so much for taking the time to contribute. A mentor or admin will review as soon as possible and approve or give further instructions."
